app/users/urls.py
from django.urls import path

from app.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from app.orders.views import ItemListView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("", ItemListView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("app.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("app.orders.urls", namespace="orders")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

app/users/models.py
from django.contrib.auth.models import AbstractUser, UserManager as BaseUserManager
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField


class UserManager(BaseUserManager):
    # pylint: disable=arguments-differ
    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        return super().create_user("", email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return super().create_superuser("", email, password, **extra_fields)


class User(AbstractUser):
    class Gender(models.TextChoices):
        MALE = "M", "Male"
        FEMALE = "F", "Female"

    username = None  # type: ignore
    email = models.EmailField("Email", blank=True, unique=True)
    gender = models.CharField("Gender", max_length=2, choices=Gender.choices, null=True)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    class Meta:
        ordering = ["first_name", "email"]
        verbose_name = "User"
        verbose_name_plural = "Users"
        db_table = "users"

    def __str__(self):
        return f"{self.name} ({self.email})"

    def get_absolute_url(self):
        return reverse("users:user-detail", kwargs={"pk": self.pk})

    def get_full_name(self):
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    @property
    def last_name_abbr(self):
        """Get an Abbreviated Last Name"""
        return self.last_name[0].upper() + "."

    @property
    def name(self):
        return self.get_full_name()

    @property
    def is_email_verified(self):
        return self.emailaddress_set.filter(email=self.email, verified=True).exists()


class BillingAddress(models.Model):
    user = models.ForeignKey("users.User", on_delete=models.PROTECT)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.country}, {self.street_address}, {self.apartment_address}, {self.zip}"

app/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["email", "gender", "first_name", "last_name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.id})

    def get_object(self):
        return User.objects.get(id=self.request.user.id)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.id})


user_redirect_view = UserRedirectView.as_view()

app/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}


{% block title %}{{ object.name }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">
    <br>
      <h2>{{ object.name }}</h2>
      {% if object.email %}
        <p>{{ object.email }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">Email</a>
    <a class="btn btn-primary" href="{% url "account_reset_password" %}" role="button">Reset Password</a>
    <a class="btn btn-primary" href="{% url "account_change_password" %}" role="button">Change Password</a>
    <a class="btn btn-primary" href="{% url 'account_logout'%}" role="button">Signout</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>

<br>
<hr>

<div class="row">

  <div class="col-sm-12">
    {% if object.billingaddress_set.all %}
    <h3> Your Address </h3>
    {% for address in  object.billingaddress_set.all %}
    <p> {{address}} </p>
    {% endfor %}
    <hr>
    {% endif %}

    {% if object.items.all %}
    <h3> Your Orders </h3>
    {% for order in  object.orders.all %}
    <p> {{order.items}} | {{order.ordered_date}} | {{order.ordered}} | {{order.ordered_date}} | {{order.refund_code}} </p>
    {% endfor %}
    <hr>
    {% endif %}

    {% if object.items.all %}
    <h3> Your Payments object.items.all </h3>
    {% for order in  object.items.all %}
    <p> {{order.payment}} </p>
    {% endfor %}
    <hr>
    {% endif %}

  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

app/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.name }}{% endblock %}

{% block content %}
  <h1>{{ user.email }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}