app/orders/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    ItemListView,
    add_item_cart,
    remove_item_cart,
    orderSummaryDetailView,
    remove_one_item_cart,
    CheckoutView,
    PromoCodeView,
    PaymentView,
    RequestRefundView,
)

app_name = "orders"

urlpatterns = [
    path("", ItemListView.as_view(), name="home"),
    path("product/<pk>", ItemDetailView.as_view(), name="product"),
    path("ordersum/", orderSummaryDetailView.as_view(), name="ordersummary"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("promo/", PromoCodeView.as_view(), name="promo"),
    path("payment/<option>/", PaymentView.as_view(), name="PaymentView"),
    path("refund/", RequestRefundView.as_view(), name="refund"),
    path("addcart/<pk>/", add_item_cart, name="addcart"),
    path("removecart/<pk>/", remove_item_cart, name="removecart"),
    path("removeitem/<pk>/", remove_one_item_cart, name="removeitem"),
]

app/users/urls.py
from django.urls import path

from app.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from app.orders.views import ItemListView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("", ItemListView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("app.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("app.orders.urls", namespace="orders")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

app/orders/models.py
import datetime
from os import path
from django.db import models
from django.shortcuts import reverse
from app.users.models import BillingAddress
from django.utils import timezone


# Create your models here.


def get_file_path(prefix: str, filename: str):
    if not prefix.endswith("/"):
        prefix += "/"
    timestamp = timezone.now().strftime("%Y-%m-%d-%H-%M-%S-%f")
    ext = path.splitext(filename)[1]
    return prefix + timestamp + ext


class Item(models.Model):
    class ItemCategory(models.TextChoices):  # A subclass of Enum
        SHIRT = "SH", "Shirt"
        SPORTWEAR = "SW", "Sport Wear"
        OUTWEAR = "OW", "Out Wear"

    class ItemLabel(models.TextChoices):  # A subclass of Enum
        PRIMARY = "PR", "primary"
        SECONDARY = "SE", "secondary"
        DANGER = "DA", "danger"

    def product_image_path(self, filename):  # pylint: disable=no-self-use
        return get_file_path("product_image/", filename)

    title = models.CharField("Title", max_length=100)
    price = models.FloatField("Price")
    category = models.CharField(
        "Category",
        max_length=2,
        choices=ItemCategory.choices,
        default=ItemCategory.SHIRT,
    )
    label = models.CharField(
        "Label",
        max_length=2,
        choices=ItemLabel.choices,
        default=ItemLabel.PRIMARY,
    )
    description = models.CharField("Description", max_length=300, blank=True, null=True)
    amount = models.IntegerField("Amount")
    image = models.ImageField(
        "Product Image",
        max_length=256,
        upload_to=product_image_path,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("orders:product", kwargs={"pk": self.id})

    def get_add_cart_url(self):
        return reverse("orders:addcart", kwargs={"pk": self.id})

    def get_remove_cart_url(self):
        return reverse("orders:removecart", kwargs={"pk": self.id})


class OrderItem(models.Model):
    user = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, null=True, blank=True
    )
    ordered = models.BooleanField("Ordered", default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField("Quantity", blank=True, null=True, default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price


class OrderStates(models.TextChoices):  # A subclass of Enum
    INITIATED = "IN", "initiated"
    DELIVERED = "DE", "delivered"
    RECEIVED = "RE", "received"
    REFUNDREQUEST = "RR", "Refund Request"
    REFUNDGRANTED = "RG", "Refund Granted"


class Order(models.Model):

    user = models.ForeignKey(
        "users.User", on_delete=models.PROTECT, related_name="items"
    )
    items = models.ManyToManyField(OrderItem)
    ordered_date = models.DateField("Ordered Date")
    ordered = models.BooleanField("Ordered", default=False)
    start_data = models.DateField("Start Date", auto_now_add=True)
    payment = models.ForeignKey(
        "Payment", on_delete=models.SET_NULL, blank=True, null=True
    )
    promo_code = models.ForeignKey(
        "PromoCode", on_delete=models.SET_NULL, blank=True, null=True
    )
    billing_address = models.ForeignKey(
        "users.BillingAddress", on_delete=models.SET_NULL, blank=True, null=True
    )
    refund_code = models.CharField("Refund Code", max_length=20, blank=True, null=True)
    state = models.CharField(
        "Order State",
        max_length=2,
        choices=OrderStates.choices,
        default=OrderStates.INITIATED,
    )

    def __str__(self):
        return self.user.name

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()
        return total

    def get_total_promocode(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()
        total -= self.promo_code.amount
        return total


class PromoCode(models.Model):
    code = models.CharField("code", max_length=15)
    amount = models.FloatField("Amount")
    expiry_date = models.DateField("Expiry Date", blank=False)

    def __str__(self):
        return self.code

    @property
    def is_expired(self):
        return self.expiry_date < datetime.date.today()


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=255)
    user = models.ForeignKey(
        "users.User", on_delete=models.SET_NULL, blank=True, null=True
    )
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}, {self.stripe_charge_id}"


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.reason}"

app/templates/base.html
{% comment %} {% load cart_count_template_tag %} {% endcomment %}
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}BuyBay{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Ecommerce app with Django!">
    <meta name="author" content="Ahmed Elfateh">
    <link rel="icon" href="{% static 'img/favicons/logo.png' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <!-- theme css -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/stripe.min.css' %}" rel="stylesheet">
    
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light white scrolling-navbar navbar-expand-lg">
        <div class="container">
          <!-- Collapse -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <!-- Links -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Just an image -->
            <a class="navbar-brand" href="{% url 'home' %}">
              <img src="{% static 'img/favicons/logo.png' %}" width="30" height="30" alt="" loading="lazy">
            </a>
          <!-- Brand -->
          <a class="navbar-brand waves-effect" href="/">
            <strong class="blue-text">Buy Bay</strong>
          </a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
              <li class="nav-item"> <a class="nav-link waves-effect" href="/checkout">Checkout</a> </li>
            </li>

          </ul>

        </div>

        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'orders:ordersummary' %}" class="nav-link waves-effect">
              {% comment %} <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_count }} </span> {% endcomment %}
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          {% comment %} <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Setting </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="dropdown-item" href="{% url 'users:detail' request.user.id  %}">{% trans "Profile" %}</a>
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="dropdown-item" href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
                </div>
          </li> {% endcomment %}
          <li class="nav-item"> <a id="sign-up-link" class="nav-link waves-effect" href="{% url 'users:detail' request.user.id  %}">{% trans "Profile" %}</a></li>
          {% else %}
          {# URL provided by django-allauth/account/urls.py #}
          <li class="nav-item"> <a id="sign-up-link" class="nav-link waves-effect" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
          {# URL provided by django-allauth/account/urls.py #}
          <li class="nav-item"> <a id="log-in-link" class="nav-link waves-effect" href="{% url 'account_login' %}">{% trans "Sign In" %}</a> </li>
          {% endif %}
        </ul>

        </div>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
    
      <div class="mt-5 pt-4">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
          {% endfor %}
        {% endif %}
    </div>

    {% endblock javascript %}
    {% include "footer.html" %}
    {% include "scripts.html" %}

  </body>
</html>

app/templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
grey lighten-3

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
              <form method="POST" class="card-body">
              {% csrf_token %}

              <!--address-->
              <div class="md-form mb-5">
                <br><br>
                {{ form.street_address }}
                <label for="address" class="">Address</label>
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
                <br><br>
                {{ form.apartment_address }}
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">Country</label>
                  {{ form.country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Zip</label>
                  {{ form.zip }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{order.items.count}}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">

            {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{order_item.quantity}} x {{order_item.item.title}}</h6>
                <span class="text-muted">Total items Price: {{order_item.get_total_item_price}}</span>
              </div>
              <div>
              </div>
            </li>
            {% endfor %}

            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Order Total: {{order.get_total}}</h6>
              </div>
            </li>

            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">{{PromoCode.code}}</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$20</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code form -->
          <form class="card p-2" action={% url 'orders:promo' %} method='POST'>
          {% csrf_token %}
            <div class="input-group">
              {% comment %} <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2"> {% endcomment %}
              {{promocodeform.code}}
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}

app/templates/footer.html
<footer class="page-footer font-small mt-4 wow fadeIn">

    <hr class="my-4">

      <div class="footer-copyright text-center py-3">© 2019 Copyright:
        <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
      </div>

  </footer>

app/templates/home.html
{% extends "base.html" %}

{% block content %}
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover; height: 200px; width=10000px">
        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover; height: 200px; width=10000px">
        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover; height: 200px; width=10000px">
        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>

  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          {% for item in object_list %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{item.get_category_display}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{item.get_label_display}}-color">bestseller</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>{{item.price}}$</strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      {% if is_paginated %}
      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <!--Arrow left-->
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="{{page_obj.page_number}}">{{page_obj.page_number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {%endif%}
        </ul>
      </nav>
      <!--Pagination-->
      {% endif %}

    </div>
  </main>

{% endblock content %}

app/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">...</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
             <td>
                <a href="{% url 'orders:removeitem' order_item.item.id %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'orders:addcart' order_item.item.id %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td> ${{ order_item.get_total_item_price }}
            <a style='color: red;' href="{% url 'orders:removecart' order_item.item.id %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Go Shopping</a>
            </td>
        </tr>
        {% endfor %}
         {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to Checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue Shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

app/templates/refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

app/templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script> 